apiVersion: v1
kind: Service
metadata:
  name: product-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    app: product
  ports:
    - name: product
      protocol: TCP
      port: 3000
      targetPort: 3000
