apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-mongo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-mongo
  template:
    metadata:
      labels:
        app: product-mongo
    spec:
      containers:
        - name: product-mongo
          image: mongo
