apiVersion: v1
kind: Service
metadata:
  name: wishlist-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    app: wishlist
  ports:
    - name: wishlist
      protocol: TCP
      port: 3000
      targetPort: 3000
