apiVersion: apps/v1
kind: Deployment
metadata:
  name: wishlist-mongo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wishlist-mongo
  template:
    metadata:
      labels:
        app: wishlist-mongo
    spec:
      containers:
        - name: wishlist-mongo
          image: mongo
