apiVersion: apps/v1
kind: Deployment
metadata:
  name: commerce-mongo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: commerce-mongo
  template:
    metadata:
      labels:
        app: commerce-mongo
    spec:
      containers:
        - name: commerce-mongo
          image: mongo
